# Generated by Django 3.0.7 on 2021-02-21 08:32

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony'), ('red', 'Red'), ('fuji', 'Fuji'), ('panasonic', 'Panasonic'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'Code'), ('mobile_review', 'Mobile Review'), ('vlogs', 'Vlogs'), ('comedy', 'Comedy'), ('gaming', 'Gaming'), ('film_making', 'Film Making'), ('cooking', 'Cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 14, 2, 16, 737050)),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'Solo'), ('small', 'Small'), ('large', 'Large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
