# Generated by Django 3.0.7 on 2021-02-21 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210221_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 8, 33, 48, 458297)),
        ),
    ]
