# Generated by Django 3.0.7 on 2021-02-21 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210221_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 17, 58, 2, 734233)),
        ),
    ]
